In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [19]:
X_train.values

array(["Y cant u try new invention to fly..i'm not joking.,",
       'Jay told me already, will do', 'Stupid.its not possible', ...,
       'Company is very good.environment is terrific and food is really nice:)',
       'Haha... Really oh no... How? Then will they deduct your lesson tmr?',
       'I am on the way to ur home'], dtype=object)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
v =CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [12]:
emails = [ 'Hey you won 20% discount',
          'I  love you']
emails_count = v.transform(emails)
model.predict(emails_count)

array([1, 0], dtype=int64)

In [13]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9901345291479821

### Pipeline implementation to make it more easy

In [14]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [15]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [16]:
clf.predict(emails)

array([1, 0], dtype=int64)